### PR TITLE
Change YearClass to an enum and use Character.isDigit()

### PR DESCRIPTION
**Pull request by trevor-e**
I like the lib, simple yet useful! While poking through it I noticed manual checks against '0' and '9' rather than using Character.isDigit().  That was an easy fix and seems to work the same.

Next, one thing that bugged me is YearClass masquerading as an enum and not actually being one.  I refactored it into an enum which wasn't too hard, allowing me to get rid of all the public static constants.  I preserved the int value so that you can still save it to SharedPreference, though it *could* be removed in favor of the ordinal value.  It does feel a bit awkward having a get(Context) method sitting in an enum, and I suppose I could push the enum to an inner class and make YearClass a wrapper.  I think it's fine how it is since it's a tighter structure, but I'll do it if someone wants me to.

How do I run the tests?  I tried running with `./gradlew test' and nothing seemed to run.  I would recommend upgrading to the 1.1 gradle plugin and using the Android Studio unit test support.

### CODE REVIEW

**Comment by SeyelentEco** [comment]
Hi Trevor,
I like the Character.isDigit() change but YearClass is really just supposed to be a year and it makes more sense for it to stay as an integer.  It makes all of the code handling it much simpler since you don't normally check against individual YearClasses and usually do things like
```
if (yearClass > YearClass.CLASS_2012) {
 // Do something for fast devices
}
```

**Comment by trevor-e** [comment]
That's a good point, I'll revert to just keep the Character.isDigit() change.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by SeyelentEco** [comment]
Sorry for the delay.  I merged the Character.isDigit() changes into master.  Thanks for your pull request!

**Comment by joeysim** [comment]
@SeyelentEco AFAIK the use of enums is not recommended in terms of memory footprint and DEX size. I'd consider going back to the static integer members.

https://www.youtube.com/watch?v=Hzs6OBcvNQE

**Comment by SeyelentEco** [comment]
@joeysim I completely agree! That's why I didn't take the enum change and only merged the Character.isDigit() change.  It was a bit confusing in this thread but here's the commit: https://github.com/facebook/device-year-class/commit/0ce9a3dcb04bb32d71a308ccb0312e78eae29352

**Comment by joeysim** [comment]
:+1:

**Pull request merged**
