### PR TITLE
Bump to 2.0.0, update README

### PR DESCRIPTION
**Pull request by zlern2k**
Re-submit this change to document how the YC classification model has changed.

### CODE REVIEW

**Comment by Atrix1987** [comment]
When can we expect 2.0.0 to be pushed to maven/jCenter ?

**Comment by dustedrob** [comment]
Is this project still alive? Been waiting for this 2.0.0 update for a while...

**Comment by SeyelentEco** [comment]
My bad, this fell off my radar and I forgot to push it.  It'll be done by the end of week.

**Comment by SeyelentEco** [comment]
Pushed to maven, verified in sample project.

**Comment by dustedrob** [comment]
Thanks!

**Pull request merged**
